name: Build/release

on:
  push:
    branches:
      - "master"

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 18.12.1

      - name: Install NPM packages for electron
        run: npm install

      - name: Install packages for Svelte
        run: |
          cd svelte-src
          npm install

      - name: Build/release Electron app
        run: npm run make

      - name: Step 3 - Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v3
        with:
          name: assets
          path: out/make/
